#!/bin/bash
# Download all logo SVGs from logoquiz.net CDN
# Run from project root: bash scripts/download-logos.sh

BASE_URL="https://d2b2fxowzdb1dz.cloudfront.net/logos"
IMG_DIR="images/logo-quiz"

# Remove old v1 directory
echo "Removing old v1 images..."
rm -rf "$IMG_DIR/v1" 2>/dev/null || echo "  (Could not remove v1 - remove manually if needed)"

# Create level directories
for i in $(seq 1 10); do
  mkdir -p "$IMG_DIR/level$i"
done

download() {
  local level="$1"
  local local_name="$2"
  local remote_file="$3"
  local dir="$IMG_DIR/level$level"

  if [ ! -f "$dir/$local_name" ]; then
    echo "  Downloading $local_name"
    curl -sf -o "$dir/$local_name" "$BASE_URL/$remote_file" || echo "    FAILED: $local_name"
  fi
}

echo ""
echo "=== Level 1 ==="
download 1 "nike.svg" "Nike%2C_Inc..svg"
download 1 "coca-cola-hint.svg" "Coca-Cola_hint.svg"
download 1 "coca-cola.svg" "Coca-Cola.svg"
download 1 "mcdonalds.svg" "McDonalds.svg"
download 1 "apple-hint.svg" "Apple_Inc._hint.svg"
download 1 "apple.svg" "Apple_Inc..svg"
download 1 "starbucks.svg" "Starbucks.svg"
download 1 "google-hint.svg" "Google_hint.svg"
download 1 "google.svg" "Google.svg"
download 1 "facebook-hint.svg" "Facebook_hint.svg"
download 1 "facebook.svg" "Facebook.svg"
download 1 "youtube-hint.svg" "YouTube_hint.svg"
download 1 "youtube.svg" "YouTube.svg"
download 1 "adidas-hint.svg" "Adidas_hint.svg"
download 1 "adidas.svg" "Adidas.svg"
download 1 "amazon-hint.svg" "Amazon_%28company%29_hint.svg"
download 1 "amazon.svg" "Amazon_%28company%29.svg"
download 1 "pepsi-hint.svg" "Pepsi_hint.svg"
download 1 "pepsi.svg" "Pepsi.svg"
download 1 "visa-hint.svg" "Visa_Inc._hint.svg"
download 1 "visa.svg" "Visa_Inc..svg"

echo ""
echo "=== Level 2 ==="
download 2 "mastercard.svg" "Mastercard.svg"
download 2 "microsoft-hint.svg" "Microsoft_hint.svg"
download 2 "microsoft.svg" "Microsoft.svg"
download 2 "gmail.svg" "Gmail.svg"
download 2 "bmw-hint.svg" "BMW_hint.svg"
download 2 "bmw.svg" "BMW.svg"
download 2 "fedex-hint.svg" "FedEx_hint.svg"
download 2 "fedex.svg" "FedEx.svg"
download 2 "disney-hint.svg" "Disney_hint.svg"
download 2 "disney.svg" "Disney.svg"
download 2 "toyota-hint.svg" "Toyota_Canada_Inc._hint.svg"
download 2 "toyota.svg" "Toyota_Canada_Inc..svg"
download 2 "walmart-hint.svg" "Walmart_hint.svg"
download 2 "walmart.svg" "Walmart.svg"
download 2 "kfc-hint.svg" "KFC_hint.svg"
download 2 "kfc.svg" "KFC.svg"
download 2 "puma-hint.svg" "Puma_hint.svg"
download 2 "puma.svg" "Puma.svg"
download 2 "honda-hint.svg" "Honda_hint.svg"
download 2 "honda.svg" "Honda.svg"
download 2 "instagram.svg" "Instagram.svg"

echo ""
echo "=== Level 3 ==="
download 3 "subway-hint.svg" "Subway_hint.svg"
download 3 "subway.svg" "Subway.svg"
download 3 "mercedes.svg" "Mercedes.svg"
download 3 "verizon-hint.svg" "Verizon_hint.svg"
download 3 "verizon.svg" "Verizon.svg"
download 3 "t-mobile-hint.svg" "T-Mobile_hint.svg"
download 3 "t-mobile.svg" "T-Mobile.svg"
download 3 "new-balance-hint.svg" "New_Balance_hint.svg"
download 3 "new-balance.svg" "New_Balance.svg"
download 3 "burger-king-hint.svg" "Burger_King_hint.svg"
download 3 "burger-king.svg" "Burger_King.svg"
download 3 "costco-hint.svg" "Costco_hint.svg"
download 3 "costco.svg" "Costco.svg"
download 3 "netflix-hint.svg" "Netflix_hint.svg"
download 3 "netflix.svg" "Netflix.svg"
download 3 "chanel-hint.svg" "Chanel_hint.svg"
download 3 "chanel.svg" "Chanel.svg"
download 3 "home-depot-hint.svg" "The_Home_Depot_hint.svg"
download 3 "home-depot.svg" "The_Home_Depot.svg"
download 3 "tesla-hint.svg" "Tesla_hint.svg"
download 3 "tesla.svg" "Tesla.svg"
download 3 "target-hint.svg" "Target_Corporation_hint.svg"
download 3 "target.svg" "Target_Corporation.svg"

echo ""
echo "=== Level 4 ==="
download 4 "shell.svg" "Shell_Oil_Company.svg"
download 4 "audi.svg" "Audi.svg"
download 4 "dominos.svg" "Dominos_Pizza.svg"
download 4 "whatsapp.svg" "WhatsApp.svg"
download 4 "taco-bell-hint.svg" "Taco_Bell_hint.svg"
download 4 "taco-bell.svg" "Taco_Bell.svg"
download 4 "heinz-hint.svg" "Heinz_hint.svg"
download 4 "heinz.svg" "Heinz.svg"
download 4 "playstation.svg" "PlayStation.svg"
download 4 "pizza-hut-hint.svg" "Pizza_Hut_hint.svg"
download 4 "pizza-hut.svg" "Pizza_Hut.svg"
download 4 "spotify-hint.svg" "Spotify_hint.svg"
download 4 "spotify.svg" "Spotify.svg"
download 4 "airbnb-hint.svg" "Airbnb_hint.svg"
download 4 "airbnb.svg" "Airbnb.svg"
download 4 "ikea-hint.svg" "IKEA_hint.svg"
download 4 "ikea.svg" "IKEA.svg"
download 4 "lg-hint.svg" "LG_hint.svg"
download 4 "lg.svg" "LG.svg"

echo ""
echo "=== Level 5 ==="
download 5 "pringles-hint.svg" "Pringles_hint.svg"
download 5 "pringles.svg" "Pringles.svg"
download 5 "snapchat.svg" "Snapchat.svg"
download 5 "general-mills.svg" "General_Mills.svg"
download 5 "reebok-hint.svg" "Reebok_hint.svg"
download 5 "reebok.svg" "Reebok.svg"
download 5 "lego-hint.svg" "Lego_hint.svg"
download 5 "lego.svg" "Lego.svg"
download 5 "cvs-hint.svg" "CVS_Pharmacy_hint.svg"
download 5 "cvs.svg" "CVS_Pharmacy.svg"
download 5 "att-hint.svg" "ATT_hint.svg"
download 5 "att.svg" "ATT.svg"
download 5 "chase-hint.svg" "Chase_Bank_hint.svg"
download 5 "chase.svg" "Chase_Bank.svg"
download 5 "adobe-hint.svg" "Adobe_hint.svg"
download 5 "adobe.svg" "Adobe.svg"
download 5 "gucci-hint.svg" "Gucci_hint.svg"
download 5 "gucci.svg" "Gucci.svg"
download 5 "bp-hint.svg" "BP_hint.svg"
download 5 "bp.svg" "BP.svg"
download 5 "wendys-hint.svg" "Wendys_hint.svg"
download 5 "wendys.svg" "Wendys.svg"

echo ""
echo "=== Level 6 ==="
download 6 "reddit-hint.svg" "Reddit_hint.svg"
download 6 "reddit.svg" "Reddit.svg"
download 6 "lowes-hint.svg" "Lowes_hint.svg"
download 6 "lowes.svg" "Lowes.svg"
download 6 "linkedin-hint.svg" "LinkedIn_hint.svg"
download 6 "linkedin.svg" "LinkedIn.svg"
download 6 "macys-hint.svg" "Macys_hint.svg"
download 6 "macys.svg" "Macys.svg"
download 6 "papa-johns-hint.svg" "Papa_Johns_Pizza_hint.svg"
download 6 "papa-johns.svg" "Papa_Johns_Pizza.svg"
download 6 "chevron-hint.svg" "Chevron_Corporation_hint.svg"
download 6 "chevron.svg" "Chevron_Corporation.svg"
download 6 "paypal-hint.svg" "PayPal_hint.svg"
download 6 "paypal.svg" "PayPal.svg"
download 6 "louis-vuitton-hint.svg" "Louis_Vuitton_hint.svg"
download 6 "louis-vuitton.svg" "Louis_Vuitton.svg"
download 6 "olive-garden-hint.svg" "Olive_Garden_hint.svg"
download 6 "olive-garden.svg" "Olive_Garden.svg"
download 6 "delta-hint.svg" "Delta_Air_Lines_hint.svg"
download 6 "delta.svg" "Delta_Air_Lines.svg"
download 6 "chilis.svg" "Chilis.svg"
download 6 "ihop-hint.svg" "IHOP_hint.svg"
download 6 "ihop.svg" "IHOP.svg"

echo ""
echo "=== Level 7 ==="
download 7 "krispy-kreme-hint.svg" "Krispy_Kreme_hint.svg"
download 7 "krispy-kreme.svg" "Krispy_Kreme.svg"
download 7 "under-armour-hint.svg" "Under_Armour_hint.svg"
download 7 "under-armour.svg" "Under_Armour.svg"
download 7 "lexus-hint.svg" "Lexus_hint.svg"
download 7 "lexus.svg" "Lexus.svg"
download 7 "ferrari-hint.svg" "Ferrari_hint.svg"
download 7 "ferrari.svg" "Ferrari.svg"
download 7 "ford-hint.svg" "Ford_hint.svg"
download 7 "ford.svg" "Ford.svg"
download 7 "kelloggs-hint.svg" "Kelloggs_hint.svg"
download 7 "kelloggs.svg" "Kelloggs.svg"
download 7 "dhl-hint.svg" "DHL_hint.svg"
download 7 "dhl.svg" "DHL.svg"
download 7 "safari.svg" "Safari.svg"
download 7 "chipotle-hint.svg" "Chipotle_Mexican_Grill_hint.svg"
download 7 "chipotle.svg" "Chipotle_Mexican_Grill.svg"
download 7 "tiktok-hint.svg" "TikTok_hint.svg"
download 7 "tiktok.svg" "TikTok.svg"
download 7 "mazda-hint.svg" "Mazda_hint.svg"
download 7 "mazda.svg" "Mazda.svg"
download 7 "nintendo-hint.svg" "Nintendo_hint.svg"
download 7 "nintendo.svg" "Nintendo.svg"

echo ""
echo "=== Level 8 ==="
download 8 "chick-fil-a-hint.svg" "Chick-fil-A_hint.svg"
download 8 "chick-fil-a.svg" "Chick-fil-A.svg"
download 8 "capital-one-hint.svg" "Capital_One_hint.svg"
download 8 "capital-one.svg" "Capital_One.svg"
download 8 "kit-kat-hint.svg" "Kit_Kat_hint.svg"
download 8 "kit-kat.svg" "Kit_Kat.svg"
download 8 "xfinity-hint.svg" "Xfinity_hint.svg"
download 8 "xfinity.svg" "Xfinity.svg"
download 8 "xbox-hint.svg" "Xbox_hint.svg"
download 8 "xbox.svg" "Xbox.svg"
download 8 "dunkin-hint.svg" "Dunkin_hint.svg"
download 8 "dunkin.svg" "Dunkin.svg"
download 8 "american-airlines-hint.svg" "American_Airlines_hint.svg"
download 8 "american-airlines.svg" "American_Airlines.svg"
download 8 "gopro-hint.svg" "GoPro_hint.svg"
download 8 "gopro.svg" "GoPro.svg"
download 8 "panera-hint.svg" "Panera_Bread_hint.svg"
download 8 "panera.svg" "Panera_Bread.svg"
download 8 "frito-lay-hint.svg" "Frito-Lay_hint.svg"
download 8 "frito-lay.svg" "Frito-Lay.svg"
download 8 "cisco-hint.svg" "Cisco_hint.svg"
download 8 "cisco.svg" "Cisco.svg"
download 8 "nestle-hint.svg" "Nestle_hint.svg"
download 8 "nestle.svg" "Nestle.svg"

echo ""
echo "=== Level 9 ==="
download 9 "southwest-airlines-hint.svg" "Southwest_Airlines_hint.svg"
download 9 "southwest-airlines.svg" "Southwest_Airlines.svg"
download 9 "red-bull-hint.svg" "Red_Bull_hint.svg"
download 9 "red-bull.svg" "Red_Bull.svg"
download 9 "holiday-inn-hint.svg" "Holiday_Inn_hint.svg"
download 9 "holiday-inn.svg" "Holiday_Inn.svg"
download 9 "united-airlines-hint.svg" "United_Airlines_hint.svg"
download 9 "united-airlines.svg" "United_Airlines.svg"
download 9 "infiniti-hint.svg" "Infiniti_hint.svg"
download 9 "infiniti.svg" "Infiniti.svg"
download 9 "caterpillar-hint.svg" "Caterpillar_hint.svg"
download 9 "caterpillar.svg" "Caterpillar.svg"
download 9 "the-north-face-hint.svg" "The_North_Face_hint.svg"
download 9 "the-north-face.svg" "The_North_Face.svg"
download 9 "venmo-hint.svg" "Venmo_hint.svg"
download 9 "venmo.svg" "Venmo.svg"
download 9 "michelin-hint.svg" "Michelin_hint.svg"
download 9 "michelin.svg" "Michelin.svg"
download 9 "ibm-hint.svg" "IBM_hint.svg"
download 9 "ibm.svg" "IBM.svg"
download 9 "texaco-hint.svg" "Texaco_hint.svg"
download 9 "texaco.svg" "Texaco.svg"
download 9 "lacoste-hint.svg" "Lacoste_hint.svg"
download 9 "lacoste.svg" "Lacoste.svg"

echo ""
echo "=== Level 10 ==="
download 10 "jbl-hint.svg" "JBL_hint.svg"
download 10 "jbl.svg" "JBL.svg"
download 10 "suzuki-hint.svg" "Suzuki_hint.svg"
download 10 "suzuki.svg" "Suzuki.svg"
download 10 "enterprise-hint.svg" "Enterprise_Rent-A-Car_hint.svg"
download 10 "enterprise.svg" "Enterprise_Rent-A-Car.svg"
download 10 "shopify-hint.svg" "Shopify_hint.svg"
download 10 "shopify.svg" "Shopify.svg"
download 10 "bosch-hint.svg" "Bosch_hint.svg"
download 10 "bosch.svg" "Bosch.svg"
download 10 "samsung-hint.svg" "Samsung_hint.svg"
download 10 "samsung.svg" "Samsung.svg"
download 10 "john-deere-hint.svg" "John_Deere_hint.svg"
download 10 "john-deere.svg" "John_Deere.svg"
download 10 "goodyear-hint.svg" "Goodyear_hint.svg"
download 10 "goodyear.svg" "Goodyear.svg"
download 10 "spacex-hint.svg" "SpaceX_hint.svg"
download 10 "spacex.svg" "SpaceX.svg"
download 10 "allstate-hint.svg" "Allstate_hint.svg"
download 10 "allstate.svg" "Allstate.svg"
download 10 "carhartt-hint.svg" "Carhartt_hint.svg"
download 10 "carhartt.svg" "Carhartt.svg"
download 10 "nasa-hint.svg" "NASA_hint.svg"
download 10 "nasa.svg" "NASA.svg"

echo ""
echo "=== Download complete ==="
echo ""

# Count downloaded files
total=$(find "$IMG_DIR" -name "*.svg" | wc -l | tr -d ' ')
echo "Total SVG files downloaded: $total"

# Verify all expected files exist
echo ""
echo "Checking for missing files..."
missing=0
for level_dir in "$IMG_DIR"/level*/; do
  level=$(basename "$level_dir")
  count=$(find "$level_dir" -name "*.svg" 2>/dev/null | wc -l | tr -d ' ')
  echo "  $level: $count files"
done
echo ""
echo "=== Fixing hint SVGs (replacing white bars with transparent masks) ==="
node "$(dirname "$0")/fix-hint-svgs.mjs"

echo ""
echo "Done!"
